export const statusCode = {
  OK: 'STATUS_200',
  CREATED: 'STATUS_201',
  NO_CONTENT: 'STATUS_204',
  BAD_REQUEST: 'STATUS_400',
  UNAUTHORIZED: 'STATUS_401',
  FORBIDDEN: 'STATUS_403',
  NOT_FOUND: 'STATUS_404',
  CONFLICT: 'STATUS_409',
  INTERNAL_SERVER_ERROR: 'STATUS_500',
  SERVICE_UNAVAILABLE: 'STATUS_503',
  DB_ERROR: 'STATUS_600',
};
