openapi: 3.0.3
info:
  title: WOOZ API v1
  description: |-
    This is a Wooz Labs Server based on the WOOZ API v1 specification.  You can find out more about
    Wooz Labs at [https://woozlabs.com](https://woozlabs.com). 

    Some useful links:
    - [Wooz Labs](https://woozlabs.com)
    - [Wooz Blog](https://blog.woozlabs.com)
    - [Wooz Trading](https://trading.woozlabs.com)
    - [Wooz Play](https://play.woozlabs.com)

  termsOfService: https://api.woozlabs.com/terms/
  contact:
    email: kim.kw8012@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Wooz Labs
  url: https://woozlabs.com
servers:
  - url: https://api.woozlabs.com/api/v1
tags:
  - name: Blog
    description: Everything about Wooz Blog
  - name: Trading
    description: Wooz Trading API
  - name: Play
    description: Wooz Play API
paths:
  /blog-contents/articles:
    get:
      tags:
        - Blog
      summary: Get article collection
      description: Get article collection determined by options
      operationId: findArticleCollection
      parameters:
        - name: options
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/RepositoryCollection"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"
            application/xml:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"
        "400":
          description: Invalid status value
      security:
        - woozlabs_auth:
            - write:user
            - read:user
  /blog-contents/articles/{articleId}:
    get:
      tags:
        - Blog
      summary: Finds article by id
      description: Find article using articleId
      operationId: findArticleById
      parameters:
        - name: articleId
          in: path
          description: ID of article to return
          required: true
          schema:
            type: string
            default: "test-id"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"
        "400":
          description: Invalid status value
      security:
        - woozlabs_auth:
            - write:user
            - read:user
  /blog-contents/articles/recommend:
    get:
      tags:
        - Blog
      summary: Find recommended articles
      description: Returns recommended articles.
      operationId: findRecommendedArticles
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"
            application/xml:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"
        "400":
          description: Invalid tag value
      security:
        - woozlabs_auth:
            - write:user
            - read:user
components:
  schemas:
    RepositoryCollection:
      type: object
      properties:
        limit:
          type: integer
          format: int64
          default: 6
        order:
          type: string
          example: "createdAt"
        sort:
          type: string
          enum:
            - desc
            - acs
        offset:
          type: number
          default: 0
        search:
          type: array
          description: Search Option
          example: ["category", "Research"]
          items:
            type: string
      xml:
        name: repositoryCollection
    Article:
      type: object
      properties:
        id:
          type: string
          example: "test-id"
        category:
          type: string
          enum:
            - Research
            - ML
            - Develop
            - Mathematics
        imageUrl:
          type: string
          example: "https://..."
        filePath:
          type: string
        author:
          type: string
          example: "Kwanwoo"
        title:
          type: string
          example: "This is title"
        subtitle:
          type: string
          example: "This is subtitle"
        views:
          type: integer
          example: 0
        articleId:
          type: string
        recommend:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      xml:
        name: article
    User:
      type: object
      properties:
        uid:
          type: string
        username:
          type: string
          example: theUser
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: James
        email:
          type: string
          example: john@email.com
        phone:
          type: string
          example: "12345"
      xml:
        name: user
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: "##default"
  requestBodies:
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/User"
  securitySchemes:
    woozlabs_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://api.woozlabs.com/oauth/authorize
          scopes:
            write:user: modify your account
            read:user: read your account
    api_key:
      type: apiKey
      name: api_key
      in: header
