# This is a basic workflow to help you get started with Actions

name: deploy@dev

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # And of course we need to goto our functions folder to deploy
      - name: Install npm packages
        run: |
          cd functions
          npm install
          cd ..
          npm install
      - name: Create Key
        id: create-key
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "key.json"
          json: ${{ secrets.FIREBASE_DEV_SERVICE_ACCOUNT }}
          dir: "functions/src/configs/"
      - name: Setting .env
        run: |
          cd functions
          echo "ENVIRONMENT=development" >> .env
          echo "STORAGE_BUCKET=${{ secrets.DEV_STORAGE_BUCKET }}" >> .env
          cat .env
          cd ..
      - name: Build production
        run: |
          cd functions
          npm run build
          cd ..
          npm run build

      - name: Check Firebase tools
        run: npx firebase-tools
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Target Firebase
        run: npx firebase-tools use default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy Firebase
        run: npx firebase-tools deploy --only storage,firestore,hosting:api,functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
